### ISSUE TITLE
CDT's accessibleViaClusterRole flag doesn't work for certain ducks

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/discovery#182]
If the duck's plural form doesn't match adding a "s" at the end (eg. Platypus -> Platypi), then `accessibleViaClusterRole` is always set to `false` even if the ClusterRole can access the duck.

# Steps to repro
1. Define a duck with a plural that doesn't follow adding an 's' at the end
1. Define a ClusterRole that can access a duck (get, list, watch)
1. Define a CDT that includes the duck and clusterrole 

Sample
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: furries-resolver
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      zoo.knative.dev/furries: "true"
rules:
- apiGroups:
  - australia.io
  resources:
  - platypi
  verbs:
  - get
  - list
  - watch

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    zoo.knative.dev/furry: "true"
  annotations:
    furries.zoo.knative.dev/v1alpha1: v1alpha2,v1beta1
    furries.zoo.knative.dev/v1beta1: v1
  name: platypi.australia.io
spec:
  group: australia.io
  names:
    kind: Platypus
    listKind: PlatypusList
    plural: platypi
    singular: platypus
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: false
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
    - name: v1alpha2
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
    - name: v1beta1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true

---
apiVersion: discovery.knative.dev/v1alpha1
kind: ClusterDuckType
metadata:
  name: furries.zoo.knative.dev
  generation: 0
spec:
  selectors:
    - labelSelector: "zoo.knative.dev/furry=true"
  role:
    roleRef:
      kind: ClusterRole
      name: furries-resolver
      apiGroup: rbac.authorization.k8s.io
  names:
    name: "Furry"
    plural: "furries"
    singular: "furry"

  versions:
    - name: "v1alpha1"
    - name: "v1beta1"
  group: zoo.knative.dev

```

# Expected
1. `kubectl get cducks/furries.zoo.knative.dev -oyaml`
     status for the duck `accessibleByClusterRole` value is `true`

# Actual
1. `kubectl get cducks/furries.zoo.knative.dev -oyaml`
     status for the duck `accessibleByClusterRole` value is `false`
